pipeline:
  name: harness_pipeline
  identifier: harness_pipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: antonychiu2
        repoName: webgoat
        build: <+input>
  stages:
    - stage:
        name: Checkmarx Scan and Fix
        identifier: Checkmarx
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
            paths: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: CheckmarxOne
                  name: CheckmarxOne_1
                  identifier: CheckmarxOne_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                      fail_on_severity: none
                    auth:
                      access_token: <+secrets.getValue("org.cx-token")>
                      type: apiKey
                    tool:
                      project_name: Webgoat
              - step:
                  type: Run
                  name: Copy Checkmarx Result
                  identifier: CopyCxResult
                  spec:
                    shell: Sh
                    image: alpine
                    command: |
                      echo "Copying Checkmarx result from /tmp..."
                      cp /tmp/cx_result.json ./cx_result.json
                      ls -lah ./cx_result.json
              - step:
                  type: Run
                  name: Mobb Autofixer
                  identifier: Mobb_Autofixer
                  spec:
                    connectorRef: account.harnessImage
                    image: node:20
                    shell: Sh
                    command: |-
                      echo "Running Mobb with cx_result.json..."
                      ls -lah
                      cat cx_result.json || echo "File not found!"
                      npx mobbdev@latest --scan-file cx_result.json
