pipeline:
  name: harness_pipeline
  identifier: harness_pipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: antonychiu2
        repoName: webgoat
        build: <+input>
  stages:
    - stage:
        name: SAST
        identifier: Checkmarx
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
            paths: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: CheckmarxOne
                  name: CheckmarxOne_1
                  identifier: CheckmarxOne_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                      fail_on_severity: none
                    auth:
                      access_token: <+secrets.getValue("org.cx-token")>
                      type: apiKey
                    tool:
                      project_name: Webgoat
              - step:
                  type: Run
                  name: Mobb Autofixer
                  identifier: Mobb_Autofixer
                  spec:
                    shell: Sh
                    command: |-
                      ls -la
                      npx mobbdev@latest
          buildIntelligence:
            enabled: false
